/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.QuadraVO;
import servicos.QuadraServicos;
import servicos.ServicosFactory;

/**
 *
 * @author berez
 */

public class GUIMenuQuadras extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel(
                new Object[][]{},
            new Object[]{"ID Quadra", "Nome Prop", "Telefone Prop", "Endereço", "CNPJ Prop", "Max. Jogadores", "Quadras", "Estabelecimento"}
    );
    
    
    /**
     * Creates new form GUIMenuQuadras
     */
    public GUIMenuQuadras() {
        initComponents();
        preencherTabela();
        limparInfos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtQuadra = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jcPesquisa = new javax.swing.JComboBox<>();
        jtfPesquisa = new javax.swing.JTextField();
        jtfEstabelecimento = new javax.swing.JTextField();
        jtfMaxJogadores = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbtnLimpar = new javax.swing.JButton();
        jbtnDeletar = new javax.swing.JButton();
        jtfNome = new javax.swing.JTextField();
        jtfQuadraID = new javax.swing.JTextField();
        jtfQuadras = new javax.swing.JTextField();
        jbtnPreencher = new javax.swing.JButton();
        jbtnConfirmar = new javax.swing.JButton();
        jbtnAlterar = new javax.swing.JButton();
        jtfTelefone = new javax.swing.JTextField();
        jtfEndereco = new javax.swing.JTextField();
        jtfCNPJ = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Menu de Quadras");

        jPanel1.setBackground(new java.awt.Color(240, 228, 206));

        jPanel2.setBackground(new java.awt.Color(240, 228, 206));

        jLayeredPane1.setBackground(new java.awt.Color(240, 228, 206));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtQuadra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtQuadra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Quadra", "Nome Prop", "Telefone Prop", "Endereço", "CNPJ Prop", "Max. Jogadores", "Quadras", "Estabelecimento"
            }
        ));
        jScrollPane1.setViewportView(jtQuadra);

        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jcPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nome", "Telefone", "Endereço", "CNPJ", "Estabelecimento" }));

        jtfPesquisa.setText("Pesquisar...");
        jtfPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jtfEstabelecimento.setText("Estabelecimento");

        jtfMaxJogadores.setText("Max. Jogadores");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-removebg 1.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jbtnLimpar.setText("Limpar");
        jbtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimparActionPerformed(evt);
            }
        });

        jbtnDeletar.setText("Deletar");
        jbtnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeletarActionPerformed(evt);
            }
        });

        jtfNome.setText("Nome");

        jtfQuadraID.setText("ID");

        jtfQuadras.setText("Quadras");

        jbtnPreencher.setText("Preencher");
        jbtnPreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPreencherActionPerformed(evt);
            }
        });

        jbtnConfirmar.setText("Confirmar Alteração");
        jbtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmarActionPerformed(evt);
            }
        });

        jbtnAlterar.setText("Alterar");
        jbtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAlterarActionPerformed(evt);
            }
        });

        jtfTelefone.setText("Telefone");

        jtfEndereco.setText("Endereço");

        try {
            jtfCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jbtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnPreencher)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnLimpar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfQuadraID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfMaxJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jtfQuadras, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAlterar)
                    .addComponent(jbtnDeletar)
                    .addComponent(jbtnConfirmar)
                    .addComponent(jbtnPreencher)
                    .addComponent(jbtnLimpar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfQuadraID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfMaxJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfQuadras, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1035, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAlterarActionPerformed
        alterarQuadra();
    }//GEN-LAST:event_jbtnAlterarActionPerformed

    private void jbtnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeletarActionPerformed
        deletarQuadra();
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbtnDeletarActionPerformed

    private void jbtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfirmarActionPerformed
        confirmarAlteracao();
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbtnConfirmarActionPerformed

    private void jbtnPreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPreencherActionPerformed
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbtnPreencherActionPerformed

    private void jbtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimparActionPerformed
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbtnLimparActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jLabel2MouseClicked


    private void preencherTabela(){
        try{
            QuadraServicos qs = ServicosFactory.getQuadraServicos();
            
            ArrayList<QuadraVO> reg = new ArrayList<>();
            
            reg = qs.buscarQuadra();
            
            for (int i = 0; i < reg.size(); i++){
                dtm.addRow(new String[] {
                    String.valueOf(reg.get(i).getIdquadra()),
                    String.valueOf(reg.get(i).getNome_responsavel()),
                    String.valueOf(reg.get(i).getTelefone_proprietario()),
                    String.valueOf(reg.get(i).getEndereco()),
                    String.valueOf(reg.get(i).getCnpj_responsavel()),
                    String.valueOf(reg.get(i).getMax_jogadores()),
                    String.valueOf(reg.get(i).getNumero_quadra()),
                    String.valueOf(reg.get(i).getNomeEstabelecimento())
                                });
            }//end of for
            
            jtQuadra.setModel(dtm);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(
                    null,
                    "Erro! GUIManuQuadra.preencherTabela" + e.getMessage());
        }
    } // end of preencher
    
    private void limparTabela(){
        dtm.setNumRows(0);
    } // end of limpar
    
    private void limparInfos() {
    // Adiciona um ouvinte de foco ao campo de texto jtfPesquisa
    jtfPesquisa.addFocusListener(new FocusListener() {
        @Override
        public void focusGained(FocusEvent e) {
            jtfPesquisa.setText("");
        }

        @Override
        public void focusLost(FocusEvent e) {
            jtfPesquisa.setText("Pesquisar...");
        }
    });

}
    
    private void deletarQuadra(){
        try{
            int linha = jtQuadra.getSelectedRow();
            
            if(linha == -1) {
                JOptionPane.showMessageDialog(
                    null,
                    "Por favor selecione uma linha!");
            }else{
                QuadraServicos qs = ServicosFactory.getQuadraServicos();
                String idquadra = (String) jtQuadra.getValueAt(linha, 0);
                qs.deletarQuadra(Integer.parseInt(idquadra));

            } 
        } catch (Exception e){
            JOptionPane.showMessageDialog(
                null,
                "Erro ao deletar Quadra! " + e.getMessage());
        }
    } // end of filtrar
    
    private void filtrar(){
        try{
            if(jtfPesquisa.getText().isEmpty() ){
                preencherTabela();
            } else {
                QuadraServicos qs = ServicosFactory.getQuadraServicos();
                String pesquisa = (String) jcPesquisa.getSelectedItem();
                
                String query = null;
                
                if(pesquisa.equals("ID")){
                    query = "where idquadra = " + jtfPesquisa.getText();
                } else if (pesquisa.equals("Nome")){
                    query = "where nome_proprietario like '%" + jtfPesquisa.getText() + "%' ";
                } else if (pesquisa.equals("Telefone")){
                    query = "where telefone_proprietario like '%" + jtfPesquisa.getText() + "%' ";
                } else if (pesquisa.equals("Endereço")){
                    query = "where endereco_quadra like '%" + jtfPesquisa.getText() + "%' ";
                } else if (pesquisa.equals("CNPJ")){
                    query = "where cnpj_proprietario like '%" + jtfPesquisa.getText() + "%' ";
                } else if (pesquisa.equals("Estabelecimento")){
                    query = "where nome_estabelecimento like '%" + jtfPesquisa.getText() + "%' ";
                }
                
                ArrayList<QuadraVO> reg = new ArrayList<>();
                
                reg = qs.filtrarQuadra(query);
                
                for ( int i = 0; i < reg.size(); i++){
                    dtm.addRow(new String[]{
                        String.valueOf(reg.get(i).getIdquadra()),
                        String.valueOf(reg.get(i).getNome_responsavel()),
                        String.valueOf(reg.get(i).getTelefone_proprietario()),
                        String.valueOf(reg.get(i).getEndereco()),
                        String.valueOf(reg.get(i).getCnpj_responsavel()),
                        String.valueOf(reg.get(i).getMax_jogadores()),
                        String.valueOf(reg.get(i).getNumero_quadra()),
                        String.valueOf(reg.get(i).getNomeEstabelecimento())
                    });
                }
                
                jtQuadra.setModel(dtm);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(
                    null,
                    "Erro ao filtrar quadra! GUIMenuQuadra.Filtrar" + e.getMessage());
        }
    }
    
    
    
    private void alterarQuadra(){
        int linha = jtQuadra.getSelectedRow();
        if(linha != -1){

            jtfQuadraID.setText((String) jtQuadra.getValueAt(linha, 0));
            jtfNome.setText((String) jtQuadra.getValueAt(linha, 1));
            jtfTelefone.setText((String) jtQuadra.getValueAt(linha, 2));
            jtfEndereco.setText((String) jtQuadra.getValueAt(linha, 3));
            jtfCNPJ.setText((String) jtQuadra.getValueAt(linha, 4));
            jtfMaxJogadores.setText((String) jtQuadra.getValueAt(linha, 5));
            jtfQuadras.setText((String) jtQuadra.getValueAt(linha, 6));
            jtfEstabelecimento.setText((String) jtQuadra.getValueAt(linha, 7));
        }else{
            JOptionPane.showMessageDialog(
                null,
                "Você não selecionou nenhuma linha!");
        }
    }
    
    public void confirmarAlteracao(){
        try{
            QuadraVO qVO = new QuadraVO();

                                   
            if(jtfNome.getText().isEmpty() ||
                    jtfTelefone.getText().isEmpty() ||
                    jtfEndereco.getText().isEmpty() ||
                    jtfCNPJ.getText().isEmpty() ||
                    jtfMaxJogadores.getText().isEmpty() ||
                    jtfQuadras.getText().isEmpty() ||
                    jtfEstabelecimento.getText().isEmpty()
                    ) {
                    JOptionPane.showMessageDialog(
                    null,
                    "Erro! Por favor insira as informacoes corretamente!",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            } else{
                qVO.setIdquadra(Integer.parseInt(jtfQuadraID.getText()));
                qVO.setNome_responsavel(jtfNome.getText());
                qVO.setTelefone_proprietario(jtfTelefone.getText());
                qVO.setEndereco(jtfEndereco.getText());
                qVO.setCnpj_responsavel(jtfCNPJ.getText());
                qVO.setMax_jogadores(Integer.parseInt(jtfMaxJogadores.getText()));
                qVO.setNumero_quadra(Integer.parseInt(jtfQuadras.getText()));
                qVO.setNomeEstabelecimento(jtfEstabelecimento.getText());
                                
                QuadraServicos qs = ServicosFactory.getQuadraServicos();
                qs.alterarQuadra(qVO);
                
                JOptionPane.showMessageDialog(
                    null,
                    "Registro alterado com sucesso!");
                
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(
                    null,
                    "Erro!" + e.getMessage());
        }
    }
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnAlterar;
    public javax.swing.JButton jbtnConfirmar;
    public javax.swing.JButton jbtnDeletar;
    public javax.swing.JButton jbtnLimpar;
    public javax.swing.JButton jbtnPreencher;
    private javax.swing.JComboBox<String> jcPesquisa;
    private javax.swing.JTable jtQuadra;
    public javax.swing.JFormattedTextField jtfCNPJ;
    public javax.swing.JTextField jtfEndereco;
    public javax.swing.JTextField jtfEstabelecimento;
    public javax.swing.JTextField jtfMaxJogadores;
    public javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfPesquisa;
    private javax.swing.JTextField jtfQuadraID;
    public javax.swing.JTextField jtfQuadras;
    public javax.swing.JTextField jtfTelefone;
    // End of variables declaration//GEN-END:variables
}
