/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author berez
 */
public class GUIPrincipal extends javax.swing.JFrame implements InternalFrameListener {
    private boolean flagGUIusuario = false;
    private boolean flagGUIProprietario = false;
    private boolean flagGUIRegistroUsuario = false;
    private boolean flagGUIRegistroProprietario = false;
    private boolean flagGUIRegistroQuadra = false;
    private boolean flagGUIRegistroPartida = false;
    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpAreaDeTrabalho = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jbtnSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        a = new javax.swing.JMenu();
        jmiMenuUsuario = new javax.swing.JMenuItem();
        jmiMenuProprietario = new javax.swing.JMenuItem();
        s = new javax.swing.JMenu();
        jmiRegistroUsuario = new javax.swing.JMenuItem();
        jmiRegistroProprietario = new javax.swing.JMenuItem();
        jmiRegistroQuadra = new javax.swing.JMenuItem();
        jmiRegistroPartida = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        jdpAreaDeTrabalho.setBackground(new java.awt.Color(240, 228, 206));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-removebg 1.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jbtnSair.setText("Sair");
        jbtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSairActionPerformed(evt);
            }
        });

        jdpAreaDeTrabalho.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpAreaDeTrabalho.setLayer(jbtnSair, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpAreaDeTrabalhoLayout = new javax.swing.GroupLayout(jdpAreaDeTrabalho);
        jdpAreaDeTrabalho.setLayout(jdpAreaDeTrabalhoLayout);
        jdpAreaDeTrabalhoLayout.setHorizontalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpAreaDeTrabalhoLayout.createSequentialGroup()
                .addContainerGap(549, Short.MAX_VALUE)
                .addGroup(jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpAreaDeTrabalhoLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(535, 535, 535))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpAreaDeTrabalhoLayout.createSequentialGroup()
                        .addComponent(jbtnSair)
                        .addGap(25, 25, 25))))
        );
        jdpAreaDeTrabalhoLayout.setVerticalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpAreaDeTrabalhoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jbtnSair)
                .addGap(46, 46, 46)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(637, Short.MAX_VALUE))
        );

        a.setText("Menu");

        jmiMenuUsuario.setText("Menu Usuario");
        jmiMenuUsuario.setEnabled(false);
        jmiMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMenuUsuarioActionPerformed(evt);
            }
        });
        jmiMenuUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmiMenuUsuarioKeyPressed(evt);
            }
        });
        a.add(jmiMenuUsuario);

        jmiMenuProprietario.setText("Menu Proprietario");
        jmiMenuProprietario.setEnabled(false);
        jmiMenuProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMenuProprietarioActionPerformed(evt);
            }
        });
        jmiMenuProprietario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmiMenuProprietarioKeyPressed(evt);
            }
        });
        a.add(jmiMenuProprietario);

        jMenuBar1.add(a);

        s.setText("Registro");

        jmiRegistroUsuario.setText("Registro de Usuario");
        jmiRegistroUsuario.setEnabled(false);
        jmiRegistroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistroUsuarioActionPerformed(evt);
            }
        });
        jmiRegistroUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmiRegistroUsuarioKeyPressed(evt);
            }
        });
        s.add(jmiRegistroUsuario);

        jmiRegistroProprietario.setText("Registro de Proprietario");
        jmiRegistroProprietario.setEnabled(false);
        jmiRegistroProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistroProprietarioActionPerformed(evt);
            }
        });
        jmiRegistroProprietario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmiRegistroProprietarioKeyPressed(evt);
            }
        });
        s.add(jmiRegistroProprietario);

        jmiRegistroQuadra.setText("Registro de Quadra");
        jmiRegistroQuadra.setEnabled(false);
        jmiRegistroQuadra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistroQuadraActionPerformed(evt);
            }
        });
        jmiRegistroQuadra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmiRegistroQuadraKeyPressed(evt);
            }
        });
        s.add(jmiRegistroQuadra);

        jmiRegistroPartida.setText("Registro de Partida");
        jmiRegistroPartida.setEnabled(false);
        jmiRegistroPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistroPartidaActionPerformed(evt);
            }
        });
        jmiRegistroPartida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmiRegistroPartidaKeyPressed(evt);
            }
        });
        s.add(jmiRegistroPartida);

        jMenuBar1.add(s);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpAreaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpAreaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMenuUsuarioActionPerformed
        abrirGUIUsuario();
    }//GEN-LAST:event_jmiMenuUsuarioActionPerformed

    private void jmiMenuUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmiMenuUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            abrirGUIUsuario();
        }
    }//GEN-LAST:event_jmiMenuUsuarioKeyPressed

    private void jmiRegistroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistroUsuarioActionPerformed
       abrirGUIRegistroUsuario();
    }//GEN-LAST:event_jmiRegistroUsuarioActionPerformed

    private void jmiRegistroUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmiRegistroUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            abrirGUIRegistroUsuario();
        }
    }//GEN-LAST:event_jmiRegistroUsuarioKeyPressed

    private void jmiRegistroProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistroProprietarioActionPerformed
       abrirGUIRegistroProprietario();
    }//GEN-LAST:event_jmiRegistroProprietarioActionPerformed

    private void jmiRegistroProprietarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmiRegistroProprietarioKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            abrirGUIRegistroProprietario();
        }
    }//GEN-LAST:event_jmiRegistroProprietarioKeyPressed

    private void jmiMenuProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMenuProprietarioActionPerformed
        abrirGUIProprietario();
    }//GEN-LAST:event_jmiMenuProprietarioActionPerformed

    private void jmiMenuProprietarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmiMenuProprietarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            abrirGUIProprietario();
        }
    }//GEN-LAST:event_jmiMenuProprietarioKeyPressed

    private void jmiRegistroQuadraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistroQuadraActionPerformed
        abrirGUIQuadra();
    }//GEN-LAST:event_jmiRegistroQuadraActionPerformed

    private void jmiRegistroQuadraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmiRegistroQuadraKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            abrirGUIQuadra();
        }
    }//GEN-LAST:event_jmiRegistroQuadraKeyPressed

    private void jmiRegistroPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistroPartidaActionPerformed
        abrirGUIRegistroPartida();
    }//GEN-LAST:event_jmiRegistroPartidaActionPerformed

    private void jmiRegistroPartidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmiRegistroPartidaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            abrirGUIRegistroPartida();
        }
    }//GEN-LAST:event_jmiRegistroPartidaKeyPressed

    private void jbtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSairActionPerformed
        dispose();
        
        GUILogin gl = new GUILogin();
        gl.setVisible(true);
    }//GEN-LAST:event_jbtnSairActionPerformed

    
    
    private void abrirGUIUsuario() {
       
        if(!flagGUIusuario){
            GUIMenuUsuario gc = new GUIMenuUsuario();

        
            jdpAreaDeTrabalho.add(gc);

        
             gc.setVisible(true);
             
             flagGUIusuario = true;
             
             gc.addInternalFrameListener(this);
        }
        
    }//fecha o método abrirGUIColadorador    
    
    private void abrirGUIProprietario() {
       
        if(!flagGUIProprietario){
            GUIMenuProprietario gp = new GUIMenuProprietario();

        
            jdpAreaDeTrabalho.add(gp);

        
             gp.setVisible(true);
             
             flagGUIProprietario = true;
             
             gp.addInternalFrameListener(this);
        }
        
    }//fecha o método abrirGUIProprietario    
    
    
    private void abrirGUIRegistroUsuario(){
        if(!flagGUIRegistroUsuario){
            GUIRegistroUsuario gr = new GUIRegistroUsuario();
            
            jdpAreaDeTrabalho.add(gr);

        
             gr.setVisible(true);
             
             flagGUIRegistroUsuario = true;
             
             gr.addInternalFrameListener(this);
        }
    }
    
    private void abrirGUIRegistroProprietario(){
        if(!flagGUIRegistroProprietario){
            GUIRegistroProprietario gp = new GUIRegistroProprietario();
            
            jdpAreaDeTrabalho.add(gp);

        
             gp.setVisible(true);
             
             flagGUIRegistroProprietario = true;
             
             gp.addInternalFrameListener(this);
        }
    }
    
    private void abrirGUIQuadra() {
       
        if(!flagGUIRegistroQuadra){
            GUIRegistroQuadra gq = new GUIRegistroQuadra();

        
            jdpAreaDeTrabalho.add(gq);

        
             gq.setVisible(true);
             
             flagGUIRegistroQuadra = true;
             
             gq.addInternalFrameListener(this);
        }
    }
    
    private void abrirGUIRegistroPartida(){
        
        if(!flagGUIRegistroPartida){
            GUIRegistroPartida gp = new GUIRegistroPartida();
            
            jdpAreaDeTrabalho.add(gp);
            
            gp.setVisible(true);
            
            flagGUIRegistroPartida = true;
            
            gp.addInternalFrameListener(this);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu a;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbtnSair;
    private javax.swing.JDesktopPane jdpAreaDeTrabalho;
    public javax.swing.JMenuItem jmiMenuProprietario;
    public javax.swing.JMenuItem jmiMenuUsuario;
    public javax.swing.JMenuItem jmiRegistroPartida;
    public javax.swing.JMenuItem jmiRegistroProprietario;
    public javax.swing.JMenuItem jmiRegistroQuadra;
    public javax.swing.JMenuItem jmiRegistroUsuario;
    private javax.swing.JMenu s;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent ife) {
            if (ife.getInternalFrame() instanceof GUIMenuUsuario){
                flagGUIusuario = false;
            } else if (ife.getInternalFrame() instanceof GUIRegistroUsuario){
                flagGUIRegistroUsuario = false;
            } else if (ife.getInternalFrame() instanceof GUIRegistroProprietario){
                flagGUIRegistroProprietario = false;
            } else if (ife.getInternalFrame() instanceof GUIMenuProprietario){
                flagGUIProprietario = false;
            }  else if (ife.getInternalFrame() instanceof GUIRegistroQuadra){
                flagGUIRegistroQuadra = false;
            } else if (ife.getInternalFrame() instanceof GUIRegistroPartida){
            flagGUIRegistroPartida = false;
            }
    }

    @Override
    public void internalFrameClosed(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameActivated(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent ife) {
        
    }
}
