/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.sun.glass.events.KeyEvent;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author berez
 */
public class GUIPrincipal extends javax.swing.JFrame implements InternalFrameListener {
    private boolean flagGUIusuario = false;
    private boolean flagGUIProprietario = false;
    private boolean flagGUIRegistroUsuario = false;
    private boolean flagGUIRegistroProprietario = false;
    private boolean flagGUIRegistroQuadra = false;
    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpAreaDeTrabalho = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        a = new javax.swing.JMenu();
        jbtnUsuario = new javax.swing.JMenuItem();
        jbtnProprietario = new javax.swing.JMenuItem();
        s = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        jdpAreaDeTrabalho.setBackground(new java.awt.Color(240, 228, 206));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-removebg 1.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jdpAreaDeTrabalho.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpAreaDeTrabalhoLayout = new javax.swing.GroupLayout(jdpAreaDeTrabalho);
        jdpAreaDeTrabalho.setLayout(jdpAreaDeTrabalhoLayout);
        jdpAreaDeTrabalhoLayout.setHorizontalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpAreaDeTrabalhoLayout.createSequentialGroup()
                .addContainerGap(549, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(535, 535, 535))
        );
        jdpAreaDeTrabalhoLayout.setVerticalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpAreaDeTrabalhoLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(637, Short.MAX_VALUE))
        );

        a.setText("Menu");

        jbtnUsuario.setText("Menu Usuario");
        jbtnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUsuarioActionPerformed(evt);
            }
        });
        jbtnUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnUsuarioKeyPressed(evt);
            }
        });
        a.add(jbtnUsuario);

        jbtnProprietario.setText("Menu Proprietario");
        jbtnProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProprietarioActionPerformed(evt);
            }
        });
        jbtnProprietario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnProprietarioKeyPressed(evt);
            }
        });
        a.add(jbtnProprietario);

        jMenuBar1.add(a);

        s.setText("Registro");

        jMenuItem1.setText("Registro de Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuItem1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem1KeyPressed(evt);
            }
        });
        s.add(jMenuItem1);

        jMenuItem2.setText("Registro de Proprietario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuItem2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem2KeyPressed(evt);
            }
        });
        s.add(jMenuItem2);

        jMenuItem3.setText("Registro de Quadra");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuItem3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem3KeyPressed(evt);
            }
        });
        s.add(jMenuItem3);

        jMenuBar1.add(s);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpAreaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpAreaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUsuarioActionPerformed
        abrirGUIUsuario();
    }//GEN-LAST:event_jbtnUsuarioActionPerformed

    private void jbtnUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            abrirGUIUsuario();
        }
    }//GEN-LAST:event_jbtnUsuarioKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       abrirGUIRegistroUsuario();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            abrirGUIRegistroUsuario();
        }
    }//GEN-LAST:event_jMenuItem1KeyPressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       abrirGUIRegistroProprietario();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem2KeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            abrirGUIRegistroProprietario();
        }
    }//GEN-LAST:event_jMenuItem2KeyPressed

    private void jbtnProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProprietarioActionPerformed
        abrirGUIProprietario();
    }//GEN-LAST:event_jbtnProprietarioActionPerformed

    private void jbtnProprietarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnProprietarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            abrirGUIProprietario();
        }
    }//GEN-LAST:event_jbtnProprietarioKeyPressed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        abrirGUIQuadra();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem3KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            abrirGUIQuadra();
        }
    }//GEN-LAST:event_jMenuItem3KeyPressed

    
    
    private void abrirGUIUsuario() {
       
        if(!flagGUIusuario){
            GUIMenuUsuario gc = new GUIMenuUsuario();

        
            jdpAreaDeTrabalho.add(gc);

        
             gc.setVisible(true);
             
             flagGUIusuario = true;
             
             gc.addInternalFrameListener(this);
        }
        
    }//fecha o método abrirGUIColadorador    
    
    private void abrirGUIProprietario() {
       
        if(!flagGUIProprietario){
            GUIMenuProprietario gp = new GUIMenuProprietario();

        
            jdpAreaDeTrabalho.add(gp);

        
             gp.setVisible(true);
             
             flagGUIProprietario = true;
             
             gp.addInternalFrameListener(this);
        }
        
    }//fecha o método abrirGUIProprietario    
    
    
    private void abrirGUIRegistroUsuario(){
        if(!flagGUIRegistroUsuario){
            GUIRegistroUsuario gr = new GUIRegistroUsuario();
            
            jdpAreaDeTrabalho.add(gr);

        
             gr.setVisible(true);
             
             flagGUIRegistroUsuario = true;
             
             gr.addInternalFrameListener(this);
        }
    }
    
    private void abrirGUIRegistroProprietario(){
        if(!flagGUIRegistroProprietario){
            GUIRegistroProprietario gp = new GUIRegistroProprietario();
            
            jdpAreaDeTrabalho.add(gp);

        
             gp.setVisible(true);
             
             flagGUIRegistroProprietario = true;
             
             gp.addInternalFrameListener(this);
        }
    }
    
    private void abrirGUIQuadra() {
       
        if(!flagGUIRegistroQuadra){
            GUIRegistroQuadra gq = new GUIRegistroQuadra();

        
            jdpAreaDeTrabalho.add(gq);

        
             gq.setVisible(true);
             
             flagGUIRegistroQuadra = true;
             
             gq.addInternalFrameListener(this);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu a;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jbtnProprietario;
    private javax.swing.JMenuItem jbtnUsuario;
    private javax.swing.JDesktopPane jdpAreaDeTrabalho;
    private javax.swing.JMenu s;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent ife) {
            if (ife.getInternalFrame() instanceof GUIMenuUsuario){
                flagGUIusuario = false;
            } else if (ife.getInternalFrame() instanceof GUIRegistroUsuario){
                flagGUIRegistroUsuario = false;
            } else if (ife.getInternalFrame() instanceof GUIRegistroProprietario){
                flagGUIRegistroProprietario = false;
            } else if (ife.getInternalFrame() instanceof GUIMenuProprietario){
                flagGUIProprietario = false;
            }  else if (ife.getInternalFrame() instanceof GUIRegistroQuadra){
                flagGUIRegistroQuadra = false;
        }
    }

    @Override
    public void internalFrameClosed(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameActivated(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent ife) {
        
    }
}
